version: '3'

services:
    backend:
        build: .
        container_name: backend
        ports:
            - '8080:8080'
        environment:
            - MINIO_SERVER_ACCESS_KEY=anyserveraccesskey
            - MINIO_SERVER_SECRET_KEY=anyserversecretkey
        depends_on:
            - db

    minio:
        image: quay.io/minio/minio
        container_name: minio
        ports:
            - '9000:9000'
            - '9090:9090'
        command: minio server /data --console-address ":9090"
        environment:
            - MINIO_ROOT_USER=admin
            - MINIO_ROOT_PASSWORD=password
            - MINIO_DEFAULT_BUCKETS=main-bucket
        volumes:
            - D:\minio\data:/data

        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
            interval: 30s
            timeout: 20s
            retries: 3

    db:
        image: postgres:14.2-alpine
        environment:
            POSTGRES_DB: img_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 6433:5432
